### ISSUE TITLE
Refuso nell'ultimo titolo dell'allegato D

### ISSUE THREAD

**Issue by ilbassa** [italia/lg-acquisizione-e-riuso-software-per-pa-docs#47]
Nell'ultimo titolo dell'allegato D (D.4) vi è un refuso nel titolo
"Pubblicazione di codice open source **non originato nel originato** nel contesto della PA"

**Comment by libremente** [comment]
Fixed by https://github.com/italia/lg-acquisizione-e-riuso-software-per-pa-docs/commit/810d08e61251164a55fe0c14d650b2d4d85e166d. Closing, thanks!
