### ISSUE TITLE
Accessibilità (Roberto Scano)

### ISSUE THREAD

**Issue by umbros** [italia/lg-acquisizione-e-riuso-software-per-pa-docs#7]
Roberto Scano

Sempre in relazione ai vincoli (2.4.2), va ricordato che nel caso di richiesta di acquisizione di soluzioni Web based (siti Web, applicazioni Web, applicazioni basate su tecnologie Web) è necessario che nei vincoli contrattuali sia previsto il rispetto dei requisiti tecnici in materia di accessibilità, pena nullità del contratto (art. 4 comma 2 legge 4/2004).

**Comment by alranel** [comment]
Questa indicazione è stata recepita nel testo delle linee guida:

https://docs.italia.it/AgID/linee-guida-riuso-software/lg-acquisizione-e-riuso-software-per-pa-docs/it/bozza/acquisizione-software/macro-fase-1-individuazione-delle-esigenze.html?highlight=accessibilità

Pertanto chiudo questa issue.
